name:
namespace:

replicaCount: 1
image:
  repository: flask-app
  tag: "latest"
  pullPolicy: IfNotPresent

# Cluster IP or Node port svc
service:
  type: LoadBalancer
  port: 80
  schema: internet-facing

env:
  S3_BUCKET_NAME: your-bucket-name

serviceAccount:
  create: true
  name: ""
  annotations: {}
  iamRoleArn: ""
