apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python-application-chart.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    {{- if .Values.serviceAccount.iamRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRoleArn }}
    {{- end }}
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
